backend:
  name: git-gateway
  repo: lsu-ddem/pathways-site
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: 
    - admin 
    - editor 

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "p5js-lesson1" 
    label: "p5js-lesson1" 
    folder: "content/unit-1-p5js/lesson_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
 
